import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Grocery Run",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Sidebar />
        <main
          className="main-content"
          style={{
            minHeight: "100vh",
            display: "flex",
            flexDirection: "column",
            width: "100%",
            boxSizing: "border-box"
          }}
        >
          {children}
        </main>
        <style>{`
          .main-content {
            padding: 2rem;
            padding-top: 6rem;
          }
          @media (max-width: 768px) {
            .main-content {
              padding: 1rem;
              padding-top: 5rem;
            }
          }
        `}</style>
      </body>
    </html>
  );
}
