import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Grocery Run",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{ display: "flex", minHeight: "100vh", flexDirection: "row" }}>
          <Sidebar />
          <main 
            style={{ 
              flex: 1, 
              padding: "2rem",
              display: "flex",
              flexDirection: "column",
              width: "100%"
            }}
          >
            {children}
          </main>
        </div>
        <style>{`
          @media (max-width: 768px) {
            div {
              flex-direction: column;
            }
            main {
              padding: 1rem;
            }
          }
        `}</style>
      </body>
    </html>
  );
}
